### PR TITLE
Add french translation

### PR DESCRIPTION
**Pull request by SamuelRiversMoore**
Hello, here is a french translation for your awesome plugin ;)

### CODE REVIEW

**Comment by hdodov** [comment]
Thank you for your contribution. I'm glad you like the plugin!

**Comment by SamuelRiversMoore** [comment]
I realize I forgot to register the link to `languages/fr.php` in `index.php > translations`. Woopsie. Should I open a new PR?

**Comment by hdodov** [comment]
Hm, I think you should. This one is already merged and I don't think it can be "reopened".

**Comment by SamuelRiversMoore** [comment]
Ok I have opened a new pull request  (#71), sorry for the omission

**Pull request merged**
